### ISSUE TITLE
Cannot send over vps web server

### ISSUE THREAD

**Issue by kujuablockchain** [yingshaoxo/kivy-chat#1]
Hi @yingshaoxo 

I am running general_client.py and Tim_asyncio_main.py using my VPS ip but the sending of the message fails. I am using port 80 which my host confirmed is open. It connects but does not send the message. Is there anything i am doing wrong?

Edit: I am running general_client.py on the web server using CGI. I also tried using cron jobs.

**Comment by yingshaoxo** [comment]
Do you run the `asyncio_server.py` first?

You should run that first in your VPS.

**Comment by kujuablockchain** [comment]
@yingshaoxo the `asyncio_server.py` does not seem to take the VPS ip, it gives the following error: 

 ```
Traceback (most recent call last):
  File "C:\Python34\lib\asyncio\base_events.py", line 905, in create_server
    sock.bind(sa)
OSError: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Jeffrey/PycharmProjects/untitled3/kivy-chat-master/kivy-chat-master/server.py", line 43, in <module>
    server = loop.run_until_complete(coro)
  File "C:\Python34\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\Python34\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Python34\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Python34\lib\asyncio\base_events.py", line 909, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 10049] error while attempting to bind on address ('41.185...', 80): the requested address is not valid in its context
```

**Comment by yingshaoxo** [comment]
Yes. Anyway, I runs well on my ubuntu server.

You could change the ip address manully by change `asyncio_server.py`(42 line).

And I recommend you use 5920 as port rather than 80 actually.

**Comment by kujuablockchain** [comment]
Just saw your edited message, when i run it in the VPS it connects but does not send. Just to be clear. I first run the `asyncio_server.py` in my cron jobs, then the `general_client.py` followed by `Tim_asyncio_main.py` which i run on my desktop right?

I have linux server, i will ask my host to open 5920

**Comment by yingshaoxo** [comment]
To be honest, I did set the default client port to 5920. So it won't work unless you change the server port to 5920.

And I think you misunderstood what I did. Actually `Tim_asyncio_main.py` and all name contains `main.py` just are clients.

And the `genetal_client.py` just another client without UI.

**Comment by kujuablockchain** [comment]
Thanks for the clarity. I have tried port 5920 but still have no success. How are you running your script on your VPS? Maybe that is what i am doing wrong by using cron jobs

**Comment by yingshaoxo** [comment]
Start it manually : `nohup python3 asyncio_server.py`


Can we talk on Telegram?

**Comment by kujuablockchain** [comment]
Ok, i'm heading out now, will let you know if it works once i'm back. Don't have a telegram account but will make one. Thanks

**Comment by kujuablockchain** [comment]
How do we connect on Telegram, I am afraid it is not popular this side of the world in South Africa, I downloaded it but it only uses cellphone numbers so cannot add @easyprogramminglanguage 

Do you have Skype or an email?

**Comment by yingshaoxo** [comment]
Send msg to yourself, and click the blue text.

**Comment by yingshaoxo** [comment]
It's too long since this issue was opened.
