### ISSUE TITLE
RuntimeError: cannot reuse already awaited coroutine [Temporary patch]

### ISSUE THREAD

**Issue by s0h3ck** [yingshaoxo/kivy-chat#2]
When running the application using Python 3.7, I got a RuntimeError.
```
$ python asyncio_main.py 
[...]
   File "asyncio_main.py", line 261, in receive_msg
     self.loop.run_until_complete(self.coro)
[...]
     return future.result()
 RuntimeError: cannot reuse already awaited coroutine
```

Temporary patch would be to modify the [receive_msg](https://github.com/yingshaoxo/kivy-chat/blob/master/asyncio_main.py#L256) method to:

```
def receive_msg(self, dt):
    try:
        self.loop.run_until_complete(self.coro)
    except:
        pass
```

**Comment by yingshaoxo** [comment]
Oh, I don't have time to check it out right now.

So you may want to use python <= 3.6 to run the code.

**Comment by yingshaoxo** [comment]
Thank you for your contribution.
